version: "3"


services:
  mongo:
    image: mongo:4
    restart: always
    ports:
      - 27020:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ff979eb04bc8f50f8e7b78abf1384dd0a12a3ff87e8bdcf373bedac19603bbcd
    volumes:
      - "./db_dump:/db_dump"